/* =========================================================================
 * ReferensiLalai.gs — Jadual skor lalai (disalin daripada sheet DATA dalam
 * TEMPLATE PAJSK SMK ASAJAYA). Dimasukkan ke Sheet REFERENSI oleh
 * sediakanSistemEPAJSK(); selepas itu admin boleh sunting terus dalam Sheet.
 * Lajur: JENIS | KOD (label) | NILAI (skor / markah minimum) | KETERANGAN.
 * ========================================================================= */

function referensiLalai() {
  return [
    ["JAWATAN", "PENGERUSI", 10, ""],
    ["JAWATAN", "KAPTEN PASUKAN", 10, ""],
    ["JAWATAN", "KETUA RUMAH", 10, ""],
    ["JAWATAN", "NAIB PENGERUSI", 8, ""],
    ["JAWATAN", "PENOLONG KETUA RUMAH", 8, ""],
    ["JAWATAN", "PENOLONG KAPTEN", 8, ""],
    ["JAWATAN", "SETIAUSAHA", 8, ""],
    ["JAWATAN", "BENDAHARI", 8, ""],
    ["JAWATAN", "PENOLONG SETIAUSAHA", 6, ""],
    ["JAWATAN", "PENOLONG BENDAHARI", 6, ""],
    ["JAWATAN", "AHLI JAWATANKUASA", 6, ""],
    ["JAWATAN", "AHLI AKTIF", 4, ""],
    ["JAWATAN", "AHLI BERDAFTAR", 2, ""],
    ["JAWATAN", "PEGAWAI WARAN KRS 1 & 2", 10, ""],
    ["JAWATAN", "STAF SARJAN KRS", 8, ""],
    ["JAWATAN", "SARJAN KRS", 7, ""],
    ["JAWATAN", "KOPERAL KRS", 6, ""],
    ["JAWATAN", "LANS KOPERAL KRS", 5, ""],
    ["JAWATAN", "AHLI AKTIF", 4, ""],
    ["JAWATAN", "AHLI BIASA", 2, ""],
    ["JAWATAN", "WARAN 2 [PKBM DARAT / LAUT / UDARA]", 10, ""],
    ["JAWATAN", "STAF SARJAN / BITARA KANAN / FLIGHT SARJAN [PKBM DARAT / LAUT / UDARA]", 8, ""],
    ["JAWATAN", "SARJAN / BINTARA MUDA / SARJAN UDARA [PKBM DARAT / LAUT / UDARA]", 7, ""],
    ["JAWATAN", "KOPERAL / LASKAR KANAN / KOPERAL UDARA [PKBM DARAT / LAUT / UDARA]", 6, ""],
    ["JAWATAN", "LANS KOPERAL / LASKAR MUDA [PKBM DARAT / LAUT / UDARA]", 5, ""],
    ["JAWATAN", "SUB INSPEKTOR / PEGAWAI KADET / PEGAWAI KANAN KADET [POLIS / JPBM / APM]", 10, ""],
    ["JAWATAN", "SARJAN MEJA / STAF SARJAN / PEGAWAI WARAN KADET [POLIS / JPBM / APM]", 8, ""],
    ["JAWATAN", "SARJAN / SARJAN KADET [POLIS / JPBM / APM]", 7, ""],
    ["JAWATAN", "KOPERAL / KOPERAL KADET [POLIS / JPBM / APM]", 6, ""],
    ["JAWATAN", "LANS KOPERAL / LANS KOPERAL KADET [POLIS / JPBM / APM]", 5, ""],
    ["JAWATAN", "INSPEKTOR KADET KOREKSIONAL / KADET PENOLONG PENGUATKUASA JPJ [KOREKSIONAL / JPJ]", 10, ""],
    ["JAWATAN", "SARJAN MEJAR KOREKSIONAL / KADET KETUA PEMBANTU PENGUATKUASA TERTINGGI JPJ [KOREKSIONAL / JPJ]", 8, ""],
    ["JAWATAN", "SARJAN KOREKSIONAL / KADET KETUA PEMBANTU PENGUATKUASA JPJ [KOREKSIONAL / JPJ]", 7, ""],
    ["JAWATAN", "KOPERAL KOREKSIONAL / KADET PEMBANTU PENGUATKUASA JPJ [KOREKSIONAL / JPJ]", 6, ""],
    ["JAWATAN", "LANS KOPERAL KOREKSIONAL / LANS KOPERAL JPJ [KOREKSIONAL / JPJ]", 5, ""],
    ["JAWATAN", "KETUA TRUP [PENGAKAP SM]", 10, ""],
    ["JAWATAN", "PENOLONG KETUA TRUP [PENGAKAP SM]", 8, ""],
    ["JAWATAN", "KETUA PATROL [PENGAKAP SM]", 7, ""],
    ["JAWATAN", "PENOLONG KETUA PATROL [PENGAKAP SM]", 6, ""],
    ["JAWATAN", "QUATEMASTER [PENGAKAP SM]", 5, ""],
    ["JAWATAN", "PENGERUSI / MEGA PUTERI [PANDU PUTERI / PPIM]", 10, ""],
    ["JAWATAN", "NAIB PENGERUSI / PUTERI MEGASARI [PANDU PUTERI / PPIM]", 8, ""],
    ["JAWATAN", "SETIAUSAHA / BENDAHARI / PUTERI BISTARIA [PANDU PUTERI / PPIM]", 7, ""],
    ["JAWATAN", "NAIB SETIAUSAHA / NAIB BENDAHARI / PUTERI KEJORA [PANDU PUTERI / PPIM]", 6, ""],
    ["JAWATAN", "AHLI JAWATANKUASA / PUTERI SAUJANA / KETUA PASUKAN [PANDU PUTERI / PPIM]", 5, ""],
    ["JAWATAN", "AHLI AKTIF / PUTERI MESTIKA / KETUA KUMPULAN [PANDU PUTERI / PPIM]", 4, ""],
    ["JAWATAN", "KETUA SEKSYEN UTAMA / PENGERUSI / SARJAN DEWASA / KETUA KADET / SARJAN MAJOR [BSMM / ST JOHN / BRIGED PUTERA]", 10, ""],
    ["JAWATAN", "PENOLONG KETUA SEKSYEN / TIMBALAN PENGERUSI / KOPERAL DEWASA / SARJAN KADET / SARJAN [BSMM / ST JOHN / BRIGED PUTERA]", 8, ""],
    ["JAWATAN", "KETUA PLATUN / LANS KOPERAL DEWASA / KOPERAL KADET / KOPERAL [BSMM / ST JOHN / BRIGED PUTERA]", 7, ""],
    ["JAWATAN", "PENOLONG KETUA PLATUN / LANS KOPERAL KADET / LANS KOPERAL [BSMM / ST JOHN / BRIGED PUTERA]", 6, ""],
    ["JAWATAN", "AHLI JAWATANKUASA [BSMM / ST JOHN / BRIGED PUTERA]", 5, ""],
    ["JAWATAN", "AHLI AKTIF - LULUS UJIAN FIRST AID / AHLI AKTIF - LULUS UJIAN PCA / AHLI AKTIF [BSMM / ST JOHN / BRIGED PUTERA]", 4, ""],
    ["JAWATAN", "PENGERUSI [BRIGED PUTERI / JOYFUL VANGUARD / RIMAP]", 10, ""],
    ["JAWATAN", "NAIB PENGERUSI [BRIGED PUTERI / JOYFUL VANGUARD / RIMAP]", 8, ""],
    ["JAWATAN", "SETIAUSAHA / BENDAHARI [BRIGED PUTERI / JOYFUL VANGUARD / RIMAP]", 7, ""],
    ["JAWATAN", "PENOLONG SETIAUSAHA / PENOLONG BENDAHARI [BRIGED PUTERI / JOYFUL VANGUARD / RIMAP]", 6, ""],
    ["JAWATAN", "AHLI JAWATANKUASA [BRIGED PUTERI / JOYFUL VANGUARD / RIMAP]", 5, ""],
    ["JAWATAN", "DRUM MAJOR [PANCARAGAM SM]", 10, ""],
    ["JAWATAN", "KETUA SEKSYEN [PANCARAGAM]", 8, ""],
    ["JAWATAN", "PENOLONG KETUA SEKSYEN [PANCARAGAM]", 7, ""],
    ["JAWATAN", "KUARTERMASTER [PANCARAGAM]", 6, ""],
    ["JAWATAN", "AHLI JAWATANKUASA [PANCARAGAM]", 5, ""],
    ["JAWATAN", "PENGERUSI / DRUM MAJOR [PANCARAGAM SR]", 10, ""],
    ["JAWATAN", "NAIB PENGERUSI / QUARTERMASTER [PANCARAGAM SR]", 8, ""],
    ["JAWATAN", "SETIAUSAHA / BENDAHARI / KETUA SEKSYEN [PANCARAGAM SR]", 7, ""],
    ["JAWATAN", "NAIB SETIAUSAHA / NAIB BENDAHARI [PANCARAGAM SR]", 6, ""],
    ["JAWATAN", "AHLI JAWATANKUASA [PANCARAGAM SR]", 5, ""],
    ["JAWATAN", "KETUA PEK [PENGAKAP SR]", 10, ""],
    ["JAWATAN", "PENOLONG KETUA PEK [PENGAKAP SR]", 8, ""],
    ["JAWATAN", "KETUA SEKAWAN [PENGAKAP SR]", 7, ""],
    ["JAWATAN", "PENOLONG KETUA SEKAWAN / QUARTERMASTER [PENGAKAP SR]", 6, ""],
    ["JAWATAN", "SARJAN [TKRS / TUSPA]", 10, ""],
    ["JAWATAN", "KOPERAL [TKRS / TUSPA]", 8, ""],
    ["JAWATAN", "LANS KOPERAL [TKRS / TUSPA]", 7, ""],
    ["JAWATAN", "PENGERUSI / LEADING BOY 1 [ST JOHN / BRIGED PUTERA / BRIGED PUTERI / BRIGED BAKTI (SR)]", 10, ""],
    ["JAWATAN", "NAIB PENGERUSI / LEADING BOY 2 [ST JOHN / BRIGED PUTERA / BRIGED PUTERI / BRIGED BAKTI (SR)]", 8, ""],
    ["JAWATAN", "SETIAUSAHA / BENDAHARI / LEADING BOY 3 [ST JOHN / BRIGED PUTERA / BRIGED PUTERI / BRIGED BAKTI (SR)]", 7, ""],
    ["JAWATAN", "NAIB SETIAUSAHA / NAIB BENDAHARI [ST JOHN / BRIGED PUTERA / BRIGED PUTERI / BRIGED BAKTI (SR)]", 6, ""],
    ["JAWATAN", "AHLI JAWATANKUASA [ST JOHN / BRIGED PUTERA / BRIGED PUTERI / BRIGED BAKTI (SR)]", 5, ""],
    ["JAWATAN", "Pengerusi / Bengkung Merah / Tali Pinggang Hitam [BELA DIRI]", 10, ""],
    ["JAWATAN", "Naib Pengerusi / Bengkung Hijau 3 dan Tali Pinggang Merah 2 [BELA DIRI]", 8, ""],
    ["JAWATAN", "Setiausaha / Bendahari : Bengkung Hijau 2 dan Tali Pinggang Merah 1 [BELA DIRI]", 7, ""],
    ["JAWATAN", "Penolong Setiausaha / Penolong Bendahari: Bengkung Hijau 1, Tali Pinggang Biru 2 [BELA DIRI]", 6, ""],
    ["JAWATAN", "Ahli Jawatankuasa: Cula 3 dan Tali Pinggang Biru 1 [BELA DIRI]", 5, ""],
    ["JAWATAN", "Ahli Aktif: Class 3, Cula 2 dan Tali pinggang Hijau 1&2 [BELA DIRI]", 4, ""],
    ["JAWATAN", "Ahli Biasa, Tali pinggang kuning 1 & 2 [BELA DIRI]", 2, ""],
    ["PELIBATAN", "PELIBATAN 1 ZON/DAERAH", 11, ""],
    ["PELIBATAN", "PELIBATAN 1 BAHAGIAN (SABAH/SARAWAK)", 12, ""],
    ["PELIBATAN", "PELIBATAN 1 NEGERI", 14, ""],
    ["PELIBATAN", "PELIBATAN 1 KEBANGSAAN", 17, ""],
    ["PELIBATAN", "PELIBATAN 1 ANTARABANGSA", 20, ""],
    ["PELIBATAN", "PELIBATAN 2 ZON/DAERAH", 8, ""],
    ["PELIBATAN", "PELIBATAN 2 BAHAGIAN (SABAH/SARAWAK)", 9, ""],
    ["PELIBATAN", "PELIBATAN 2 NEGERI", 10, ""],
    ["PELIBATAN", "PELIBATAN 2 KEBANGSAAN", 12, ""],
    ["PELIBATAN", "PELIBATAN 2 ANTARABANGSA", 15, ""],
    ["PELIBATAN", "PELIBATAN 3 ZON/DAERAH", 10, ""],
    ["PELIBATAN", "PELIBATAN 3 BAHAGIAN (SABAH/SARAWAK)", 8, ""],
    ["PELIBATAN", "PELIBATAN 3 NEGERI", 6, ""],
    ["PELIBATAN", "PELIBATAN 3 KEBANGSAAN", 5, ""],
    ["PELIBATAN", "PELIBATAN 3 ANTARABANGSA", 4, ""],
    ["PELIBATAN", "SEKOLAH", 0, ""],
    ["PENCAPAIAN", "JOHAN SEKOLAH", 8, ""],
    ["PENCAPAIAN", "JOHAN ZON", 11, ""],
    ["PENCAPAIAN", "JOHAN DAERAH", 11, ""],
    ["PENCAPAIAN", "JOHAN NEGERI", 14, ""],
    ["PENCAPAIAN", "JOHAN KEBANGSAAN", 17, ""],
    ["PENCAPAIAN", "JOHAN ANTARABANGSA", 20, ""],
    ["PENCAPAIAN", "NAIB JOHAN SEKOLAH", 7, ""],
    ["PENCAPAIAN", "NAIB JOHAN ZON", 10, ""],
    ["PENCAPAIAN", "NAIB JOHAN DAERAH", 10, ""],
    ["PENCAPAIAN", "NAIB JOHAN NEGERI", 13, ""],
    ["PENCAPAIAN", "NAIB JOHAN KEBANGSAAN", 16, ""],
    ["PENCAPAIAN", "NAIB JOHAN ANTARABANGSA", 19, ""],
    ["PENCAPAIAN", "KETIGA SEKOLAH", 6, ""],
    ["PENCAPAIAN", "KETIGA ZON", 9, ""],
    ["PENCAPAIAN", "KETIGA DAERAH", 9, ""],
    ["PENCAPAIAN", "KETIGA NEGERI", 12, ""],
    ["PENCAPAIAN", "KETIGA KEBANGSAAN", 15, ""],
    ["PENCAPAIAN", "KETIGA ANTARABANGSA", 18, ""],
    ["PENCAPAIAN", "KEEMPAT SEKOLAH", 5, ""],
    ["PENCAPAIAN", "KEEMPAT ZON/DAERAH", 8, ""],
    ["PENCAPAIAN", "KEEMPAT NEGERI", 11, ""],
    ["PENCAPAIAN", "KEEMPAT KEBANGSAAN", 14, ""],
    ["PENCAPAIAN", "KEEMPAT ANTARABANGSA", 17, ""],
    ["PENCAPAIAN", "KELIMA SEKOLAH", 4, ""],
    ["PENCAPAIAN", "KELIMA ZON/DAERAH", 7, ""],
    ["PENCAPAIAN", "KELIMA NEGERI", 10, ""],
    ["PENCAPAIAN", "KELIMA KEBANGSAAN", 13, ""],
    ["PENCAPAIAN", "KELIMA ANTARABANGSA", 16, ""],
    ["PENCAPAIAN", "JOHAN BAHAGIAN (SABAH/SARAWAK)", 12, ""],
    ["PENCAPAIAN", "NAIB JOHAN BAHAGIAN (SABAH/SARAWAK)", 11, ""],
    ["PENCAPAIAN", "KETIGA BAHAGIAN (SABAH/SARAWAK)", 10, ""],
    ["PENCAPAIAN", "KEEMPAT BAHAGIAN (SABAH/SARAWAK)", 9, ""],
    ["PENCAPAIAN", "KELIMA BAHAGIAN (SABAH/SARAWAK)", 8, ""],
    ["KOMITMEN", "Menunjukkan Kepimpinan", 3, ""],
    ["KOMITMEN", "Mengurus Aktiviti", 3, ""],
    ["KOMITMEN", "Membantu guru atau rakan", 2, ""],
    ["KOMITMEN", "Menyedia Peralatan", 2, ""],
    ["KOMITMEN", "Mengemas Peralatan", 2, ""],
    ["KOMITMEN", "Membersih Kawasan", 2, ""],
    ["KOMITMEN", "Menepati Waktu", 2, ""],
    ["KOMITMEN", "Menunjukkan Minat", 2, ""],
    ["KOMITMEN", "Menunjukkan Kesungguhan", 2, ""],
    ["KOMITMEN", "Mengikut Arahan", 2, ""],
    ["KOMITMEN", "Mencuba", 2, ""],
    ["KOMITMEN", "Memberi Kerjasama", 2, ""],
    ["KOMITMEN", "Mana-mana Nilai Murni Yang Boleh Diperhatikan", 2, ""],
    ["KHIDMAT_SUMBANGAN", "Murid yang didaftarkan sebagai atlet atau peserta program / pertandingan / Karnival / kursus", 10, ""],
    ["KHIDMAT_SUMBANGAN", "Melibatkan kemahiran khusus–berkaitan aspek teknikal (pengadil, jurulatih pasukan, dll yang berkaitan dengan aspek teknikal)", 10, ""],
    ["KHIDMAT_SUMBANGAN", "Penglibatan murid yang terlibat dalam aktiviti seperti persembahan selingan", 8, ""],
    ["KHIDMAT_SUMBANGAN", "Membantu dari segi menjayakan aktiviti kelab persatuan sukan sekolah seperti mengambil bahagian dalam perbarisan atau persembahan, kumpulan sorak/penyokong, dan yang berkaitan.", 5, ""],
    ["KEHADIRAN", "1", 3.33, ""],
    ["KEHADIRAN", "2", 6.66, ""],
    ["KEHADIRAN", "3", 9.99, ""],
    ["KEHADIRAN", "4", 13.32, ""],
    ["KEHADIRAN", "5", 16.65, ""],
    ["KEHADIRAN", "6", 19.98, ""],
    ["KEHADIRAN", "7", 23.21, ""],
    ["KEHADIRAN", "8", 26.64, ""],
    ["KEHADIRAN", "9", 29.97, ""],
    ["KEHADIRAN", "10", 33.3, ""],
    ["KEHADIRAN", "11", 36.63, ""],
    ["KEHADIRAN", "12", 40, ""],
    ["ANUGERAH_KHAS", "ANUUGERAH TUNAS JAYA KEMENTERIAN WANITA", 10, ""],
    ["ANUGERAH_KHAS", "ANUGERAH KO & SUKAN PERINGKAT KEBANGSAAN", 10, ""],
    ["ANUGERAH_KHAS", "ANUGERAH KO & SUKAN PERINGKAT NEGERI", 8, ""],
    ["ANUGERAH_KHAS", "ANUGERAH KO & SUKAN PERINGKAT ZON/DAERAH/BAHAGIAN", 6, ""],
    ["ANUGERAH_KHAS", "ANUGERAH KO & SUKAN PERINGKAT SEKOLAH", 4, ""],
    ["ANUGERAH_KHAS", "ANUGERAH & PENGHARGAAN KHAS PERINGKAT KEBANGSAAN", 10, ""],
    ["ANUGERAH_KHAS", "ANUGERAH & PENGHARGAAN KHAS PERINGKAT NEGERI", 7, ""],
    ["ANUGERAH_KHAS", "ANUGERAH & PENGHARGAAN KHAS PERINGKAT ZON/DAERAH/BAHAGIAN", 5, ""],
    ["ANUGERAH_KHAS", "ANUGERAH & PENGHARGAAN KHAS PERINGKAT SEKOLAH", 3, ""],
    ["ANUGERAH_KHAS", "EMAS PENYERTAAN BUKAN KPM ANTARABANGSA", 5, ""],
    ["ANUGERAH_KHAS", "PERAK PENYERTAAN BUKAN KPM ANTARABANGSA", 4, ""],
    ["ANUGERAH_KHAS", "GANGSA PENYERTAAN BUKAN KPM ANTARABANGSA", 3, ""],
    ["ANUGERAH_KHAS", "EMAS ANUGERAH REMAJA PERDANA KBS", 10, ""],
    ["ANUGERAH_KHAS", "PERAK ANUGERAH REMAJA PERDANA KBS", 7, ""],
    ["ANUGERAH_KHAS", "GANGSA ANUGERAH REMAJA PERDANA KBS", 5, ""],
    ["ANUGERAH_KHAS", "PESERTA MFLS TIER 3", 7, ""],
    ["ANUGERAH_KHAS", "PESERTA MFLAS TIER 2", 4, ""],
    ["ANUGERAH_KHAS", "PENGAKAP RAJA", 10, ""],
    ["ANUGERAH_KHAS", "PANDU PUTERI RAJA", 10, ""],
    ["ANUGERAH_KHAS", "PUTERI AZ-ZAHRA [PPIM]", 10, ""],
    ["ANUGERAH_KHAS", "GRAND PRIOR - SJAM", 10, ""],
    ["ANUGERAH_KHAS", "MEWAKILI NEGARA DALAM SUKAN OLIMPIK/ SUKAN KOMANWEL/ SUKAN ASIA/ SUKAN ASIA TENGGARA", 10, ""],
    ["PERKHIDMATAN", "Ketua Murid", 10, ""],
    ["PERKHIDMATAN", "Timbalan/Penolong Ketua Murid", 8, ""],
    ["PERKHIDMATAN", "Pengurusan Utama yang ditubuhkan untuk membantu sekolah Pengawas/ Ketua Asrama /Ketua PRS /BADAR/Pengerusi Badan-Badan Perkhidmatan Sekolah", 7, ""],
    ["PERKHIDMATAN", "Penolong Ketua Asrama / Pengawas Pusat Sumber/BADAR", 6, ""],
    ["PERKHIDMATAN", "AJK Utama Badan-badan Perkhidmatan atau Pengurusan / Bendahari / Setiausaha / Ketua Biro -Asrama / PRS /BADAR/Penerima sijil dan lencana SLAD / PROSTAR / Pegawas Koperasi//Ketua Kelas / Ketua Tingkatan/", 5, ""],
    ["PERKHIDMATAN", "Ahli-ahli J/Kuasa Perkhidmatan dan Sokongan-AJK Kecil Biro / Ketua Bilik / Ketua Dorm/BADAR/Penerima sijil SLAD / PROSTAR/Penolong Ketua Kelas / Penolong Ketua Bilik", 3, ""],
    ["NILAM", "1 BINTANG SEKOLAH", 3, ""],
    ["NILAM", "2 BINTANG SEKOLAH", 4, ""],
    ["NILAM", "3 BINTANG SEKOLAH", 5, ""],
    ["NILAM", "4 BINTANG SEKOLAH", 6, ""],
    ["NILAM", "5 BINTANG SEKOLAH", 7, ""],
    ["NILAM", "1 BINTANG Z/D/B", 4, ""],
    ["NILAM", "2 BINTANG Z/D/B", 5, ""],
    ["NILAM", "3 BINTANG Z/D/B", 6, ""],
    ["NILAM", "4 BINTANG Z/D/B", 7, ""],
    ["NILAM", "5 BINTANG Z/D/B", 8, ""],
    ["NILAM", "5 BINTANG NEGERI", 9, ""],
    ["NILAM", "5 BINTANG KEBANGSAAN", 10, ""],
    ["KHIDMAT_MASYARAKAT", "Murid tidak melaksanakan aktiviti khidmat masyarakat", 0, ""],
    ["KHIDMAT_MASYARAKAT", "Murid melaksanakan 5 aktiviti khidmat masyarakat secara sangat aktif, komited dan menunjukkan potensi diri yang tinggi", 10, ""],
    ["KHIDMAT_MASYARAKAT", "Murid melaksanakan 4 aktiviti khidmat masyarakat secara aktif, komited dan menunjukkan potensi diri yang tinggi", 8, ""],
    ["KHIDMAT_MASYARAKAT", "Murid melaksanakan 3 aktiviti khidmat masyarakat secara komited dan menunjukkan kesungguhan", 6, ""],
    ["KHIDMAT_MASYARAKAT", "Murid melaksanakan 2 aktiviti khidmat masyarakat secara komited dan menunjukkan minat", 4, ""],
    ["KHIDMAT_MASYARAKAT", "Murid melaksanakan 1 aktiviti khidmat masyarakat di tahap minimum", 2, ""],
    ["TIMMS_PISA", "PENYERTAAN DI PERINGKAT ANTARABANGSA YANG MENCAPAI TAHAP CEMERLANG", 10, ""],
    ["TIMMS_PISA", "PENYERTAAN DI PERINGKAT ANTARABANGSA", 8, ""],
    ["TIMMS_PISA", "PENYERTAAN DI PERINGKAT KEBANGSAAN", 6, ""],
    ["TUGAS_KHAS", "Peserta / Atlet Persembahan Padang, Perarakan, Perbarisan, Kejohanan sempena Sambutan Hari Kebangsaan peringkat Kebangsaan / Sukan SEA / Sukan ASIA / Bulan Sukan Negara peringkat Kebangsaan", 7, ""],
    ["TUGAS_KHAS", "Peserta Persembahan Padang, Perarakan dan Perbarisan sempena Sambutan Hari Kebangsaan / Hari Sukan Negara peringkat Negeri", 6, ""],
    ["TUGAS_KHAS", "Sukarelawan program sukan/kokurikulum/seni peringkat antarabangsa yang dianjurkan dalam negara", 5, ""],
    ["TUGAS_KHAS", "Sukarelawan program sukan/kokurikulum/seni peringkat antarabangsa yang dianjurkan dalam negara (B)", 3, ""],
    ["GRED", "E", 1, "TIDAK MEMUASKAN||Penglibatan Dan Tahap Pencapaian Anda Tidak Memuaskan Dalam Aktiviti Yang Disertai. Anda Perlu Mempertingkatkan Motivasi Diri Untuk Mencapai Tahap Prestasi Yang Lebih Baik"],
    ["GRED", "D", 20, "KURANG MEMUASKAN||Penglibatan Anda Kurang Dan Tidak Menunjukkan Kesungguhan Dalam Aktiviti Yang Disertai. Tingkatkan Usaha Anda Dalam Aktiviti Yang Disertai Supaya Anda Dapat Mencapai Tahap Prestasi Yang Lebih Baik"],
    ["GRED", "C", 40, "BAIK||Penglibatan Dan Penyertaan Anda Dalam Aktiviti Yang Disertai Adalah Memuaskan. Anda Perlu Dan Mampu Untuk Lebih Berusaha Bagi Meningkatkan Prestasi Ke Tahap Pencapaian Yang Lebih Baik Dalam Aktiviti Yang Disertai"],
    ["GRED", "B", 60, "KEPUJIAN||Tahniah! Anda merupakan seorang yang aktif, komited dan menunjukkan minat yang memuaskan dalam aktiviti yang disertai. Anda boleh mempertingkatkan potensi diri dan prestasi dalam aktiviti yang diceburi sekiranya memberi lebih penumpuan dalam aktiviti tersebut."],
    ["GRED", "A", 80, "CEMERLANG||Syabas! Anda seorang yang sangat aktif, komited dan menunjukan potensi diri yang tinggi dalam aktiviti yang disertai. Anda hendaklah mengekalkan kecemerlangan prestasi dan mempertingkatkan usaha untuk berjaya dalam bidang yang diceburi dan diminati. Semoga kecemerlangan ini boleh diteladani oleh yang lain!"]
  ];
}
